# Generated by Django 5.0.6 on 2024-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="descricao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
